sudo: required
services:
  - docker

before_install:
  - docker build -t quiglen3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true quiglen3/react-test npm run test

after_success:
  - docker build -t quiglen3/multi-client:5 ./client
  - docker build -t quiglen3/multi-nginx ./nginx
  - docker build -t quiglen3/multi-server ./server
  - docker build -t quiglen3/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push quiglen3/multi-client:5
  - docker push quiglen3/multi-nginx
  - docker push quiglen3/multi-server
  - docker push quiglen3/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-335821362563
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
